version: "3.7"

services:
  app:
    image: ghcr.io/beeracademy/beta-game
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.beta-academy-beer.rule=Host(`beta.academy.beer`)
      - traefik.http.services.beta-academy-beer.loadbalancer.server.port=80

networks:
  traefik:
    external: true
